FROM maven:3.8-openjdk-17 as builder

SHELL ["/bin/bash", "-c"]

COPY . /app

WORKDIR /app

RUN mvn dependency:resolve -f app/pom.xml && mvn package -f app/pom.xml && app/target/app.jar . && rm -rf app/

FROM openjdk:8-jre-alpine

COPY --from=builder /app /app

WORKDIR /app

# CMD [ "java", "-jar", "app.jar" ]
